name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  analyze-and-test:
    name: Lint + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable
          cache: true

      - run: flutter pub get

      - name: Générer le code (Drift)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyse statique
        run: flutter analyze --fatal-infos

      - name: Vérifier le formatage
        run: dart format --output=none --set-exit-if-changed .

      - name: Tests
        run: flutter test --coverage

      - name: Publier la couverture
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info

  build-android:
    name: Build Android (debug)
    needs: analyze-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable
          cache: true

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK debug
        run: flutter build apk --debug

  build-ios:
    name: Build iOS (sans signature)
    needs: analyze-and-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable
          cache: true

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign
